// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Books.Api.Persistance.Migrations;

[DbContext(typeof(BooksDbContext))]
partial class BooksDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

        modelBuilder.Entity("Books.Api.Models.Book", b =>
            {
                b.Property<string>("Isbn")
                    .HasColumnType("TEXT");

                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("PageCount")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("ReleaseDate")
                    .HasColumnType("TEXT");

                b.Property<string>("ShortDescription")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Isbn");

                b.ToTable("Books");
            });
#pragma warning restore 612, 618
    }
}
